ContactCase.Web/Models/ContactInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ContactCase.Web.Models
{
    public class ContactInfo
    {
        public Guid Id { get; set; }
        public Guid ContactId { get; set; }
        public string Value { get; set; }
        public string InfoType { get; set; }
    }
}

ContactCase.Web/Models/ContactModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ContactCase.Web.Models
{
    public class ContactModel
    {
        public Guid Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CompanyName { get; set; }
        public DateTime CreateDate { get; set; }

        public List<ContactInfo> Infos { get; set; } = new List<ContactInfo>();
    }
}

ContactCase.Web/Models/ErrorViewModel.cs
using System;

namespace ContactCase.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ContactCase.Web/Models/ReportModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ContactCase.Web.Models
{
    public class ReportModel
    {
        public Guid Id { get; set; }
        public string Tag { get; set; }
        public int Count { get; set; }
        public DateTime CreateDate { get; set; }
        public bool Status { get; set; }
    }
}

ContactCase.Web/Controllers/ContactController.cs
using ContactCase.Web.ApiClients;
using ContactCase.Web.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ContactCase.Web.Controllers
{
    public class ContactController : Controller
    {
        private readonly ContactClient _contactClient;

        public ContactController(ContactClient contactClient) => _contactClient = contactClient;
        public async Task<IActionResult> Index([FromQuery] int pageIndex = 0, [FromQuery] int pageSize = 20) => View(await _contactClient.GetContacts(pageIndex, pageSize));

        public IActionResult Create() => View(new ContactModel());

        [HttpPost]
        public async Task<IActionResult> Create(ContactModel model)
        {
            var result = await _contactClient.Create(model);
            if (result) 
                return RedirectToAction("Index");

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete([FromRoute] Guid? id)
        {
            if (!id.HasValue || id.Value == Guid.Empty)
                return StatusCode(404);

            if (await _contactClient.Delete(id.Value))
                return Ok();

            return StatusCode(404);
        }

        public async Task<IActionResult> Edit(Guid? id)
        {
            if (!id.HasValue) {
                StatusCode(404, "Not Found");
                return RedirectToAction("Index");
            }
            var model = await _contactClient.GetById(id.Value);
            if (model == null)
                StatusCode(404, "Not Found");
            else
                return View(model);

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ContactModel model)
        {
            if (ModelState.IsValid) {
                var updateResult = await _contactClient.Update(model);
                if (updateResult) return RedirectToAction("Index");
            }

            return View(model);
        }
    }
}

ContactCase.Web/Controllers/HomeController.cs
using ContactCase.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ContactCase.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ContactCase.Web/Controllers/ReportController.cs
using ContactCase.Web.ApiClients;
using ContactCase.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace ContactCase.Web.Controllers
{
    public class ReportController : Controller
    {
        private readonly ReportApiClient _reportApiClient;

        public ReportController(ReportApiClient reportApiClient)
        {
            _reportApiClient = reportApiClient;
        }
        public async Task<IActionResult> Index([FromQuery] int pageIndex = 0, [FromQuery] int pageSize = 20)
        {
            var model = await _reportApiClient.GetReports(pageIndex, pageSize);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(string Tag)
        {
            ReportModel model = new ReportModel();
            model.Tag = Tag;

            if (ModelState.IsValid) {
                var createResult = await _reportApiClient.CreateReport(Tag);
                if (createResult is not null) {
                    return RedirectToAction("Index");
                }
            }

            return View(model);
        }
    }
}

ContactCase.Web/Views/Contact/Create.cshtml
@model ContactModel


@{ ViewData["Title"] = "New Contact"; }



<div class="text-center">
    <h1 class="display-4">New Contact</h1>
</div>

<form asp-action="Create" asp-controller="Contact" asp-area="" method="post" role="form" novalidate>
    <div class="row mt-5">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <h4>Contact</h4>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label asp-for="FirstName">FirstName</label>
                        <input type="text" class="form-control" asp-for="FirstName" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="LastName">LastName</label>
                        <input type="text" class="form-control" asp-for="LastName" />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="CompanyName">CompanyName</label>
                        <input type="text" class="form-control" asp-for="CompanyName" />
                        <span asp-validation-for="CompanyName" class="text-danger"></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <h4>Contact Info</h4>
                </div>
                <div class="card-body">
                    <table class="table table-bordered table-striped" id="table-info">
                        <thead>
                            <tr>
                                <th>Type</th>
                                <th>Value</th>
                            </tr>
                        </thead>
                        <tbody>
                            @for (int i = 0; i < Model.Infos.Count; i++)
                            {
                                var item = Model.Infos[i];
                <tr>
                    <td>
                        <input type="hidden" asp-for="Infos[i].Id" />
                        <input type="hidden" asp-for="Infos[i].ContactId" />
                        <input type="hidden" asp-for="Infos[i].InfoType" />
                        @item.InfoType
                    </td>
                    <td>
                        <input type="hidden" asp-for="Infos[i].Value" />
                        @item
                    </td>
                    <td><button type="button" onclick="removeinforow(this)" class="btn btn-sm btn-danger">Remove</button></td>
                </tr>}
                        </tbody>
                        <tfoot>
                            <tr>
                                <td><input type="text" class="form-control" id="info-type" placeholder="Type" /></td>
                                <td><input type="text" class="form-control" id="info-value" placeholder="Value" /></td>
                                <td><button type="button" onclick="addinforow()" class="btn btn-sm btn-success">Add</button></td>
                            </tr>
                        </tfoot>
                    </table>

                </div>
            </div>
        </div>
        <div class="col-12 text-right mt-3">
            <button type="submit" class="btn btn-sm btn-primary">Save</button>
        </div>
    </div>
</form>
@section scripts {
    <script>

        function addinforow() {
            var rowcount = $("#table-info > tbody > tr").length;

            var idName = "Infos[" + rowcount + "].Id";
            var contactIdName = "Infos[" + rowcount + "].ContactId";
            var infoTypeName = "Infos[" + rowcount + "].InfoType";

            var infoValue = $("#info-type").val();
            $("#info-type").val("");

            var valueName = "Infos[" + rowcount + "].Value";
            var valueValue = $("#info-value").val();
            $("#info-value").val("");

            var row = `<tr>
                           <td>
                               <input type="hidden" name="${idName}" />
                               <input type="hidden" name="${contactIdName}" />
                               <input type="hidden" name="${infoTypeName}" value="${infoValue}" />
                               ${infoValue}
                           </td>
                           <td>
                               <input type="hidden" name="${valueName}" value="${valueValue}" />
                               ${valueValue}
                           </td>
                           <td><button type="button" name="btn-remove-row" class="btn btn-sm btn-danger">Remove</button></td>
                       </tr>`

            $("#table-info tbody").append(row);
        }

        function removeinforow(e) {
            $(e).parents("tr").remove();
        }
    </script>

}

ContactCase.Web/Views/Contact/Edit.cshtml
@model ContactModel


@{ ViewData["Title"] = "Edit Contact"; }



<div class="text-center">
    <h1>Edit Contact</h1>
</div>

<form asp-action="Update" asp-controller="Contact" asp-area="" method="post" role="form" novalidate>
    <div class="row mt-5">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <h4>Contact</h4>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label asp-for="FirstName">FirstName</label>
                        <input type="text" class="form-control" asp-for="FirstName" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="LastName">LastName</label>
                        <input type="text" class="form-control" asp-for="LastName" />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="CompanyName">CompanyName</label>
                        <input type="text" class="form-control" asp-for="CompanyName" />
                        <span asp-validation-for="CompanyName" class="text-danger"></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <h4>Contact Info</h4>
                </div>
                <div class="card-body">
                    <table class="table table-bordered table-striped" id="table-info">
                        <thead>
                            <tr>
                                <th>Type</th>
                                <th>Value</th>
                            </tr>
                        </thead>
                        <tbody>
                            @for (int i = 0; i < Model.Infos.Count; i++)
                            {
                                var item = Model.Infos[i];
                <tr>
                    <td>
                        <input type="hidden" asp-for="Infos[i].Id" />
                        <input type="hidden" asp-for="Infos[i].ContactId" />
                        <input type="hidden" asp-for="Infos[i].InfoType" />
                        @item.InfoType
                    </td>
                    <td>
                        <input type="hidden" asp-for="Infos[i].Value" />
                        @item.Value
                    </td>
                    <td><button type="button" onclick="removeinforow(this)" class="btn btn-sm btn-danger">Remove</button></td>
                </tr>}
                        </tbody>
                        <tfoot>
                            <tr>
                                <td><input type="text" class="form-control" id="info-type" placeholder="Type" /></td>
                                <td><input type="text" class="form-control" id="info-value" placeholder="Value" /></td>
                                <td><button type="button" onclick="addinforow()" class="btn btn-sm btn-success">Add</button></td>
                            </tr>
                        </tfoot>
                    </table>

                </div>
            </div>
        </div>
        <div class="col-12 text-right mt-3">
            <button type="submit" class="btn btn-sm btn-primary">Save</button>
        </div>
    </div>
</form>


@section scripts {
    <script>

        function addinforow() {
            var rowcount = $("#table-info > tbody > tr").length;

            var idName = "Infos[" + rowcount + "].Id";
            var contactIdName = "Infos[" + rowcount + "].ContactId";
            var infoTypeName = "Infos[" + rowcount + "].InfoType";

            var infoValue = $("#info-type").val();
            $("#info-type").val("");

            var valueName = "Infos[" + rowcount + "].Value";
            var valueValue = $("#info-value").val();
            $("#info-value").val("");

            var row = `<tr>
                               <td>
                                   <input type="hidden" name="${idName}" />
                                   <input type="hidden" name="${contactIdName}" />
                                   <input type="hidden" name="${infoTypeName}" value="${infoValue}" />
                                   ${infoValue}
                               </td>
                               <td>
                                   <input type="hidden" name="${valueName}" value="${valueValue}" />
                                   ${valueValue}
                               </td>
                               <td><button type="button" name="btn-remove-row" class="btn btn-sm btn-danger">Remove</button></td>
                           </tr>`

            $("#table-info tbody").append(row);
        }

        function removeinforow(e) {
            $(e).parents("tr").remove();
        }
    </script>

}

ContactCase.Web/Views/Contact/Index.cshtml
@{ ViewData["Title"] = "Contacts"; }
@model List<ContactModel>

<div class="text-center">
    <h1 class="display-4">Contacts</h1>
</div>

<a asp-action="Create" asp-controller="Contact" asp-area="" class="btn btn-sm btn-primary mb-3">Create</a>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>FirstName</th>
            <th>LastName</th>
            <th>CompanyName</th>
            <th>CreateDate</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Any())
        {
@foreach (var contact in Model)
{
<tr data-id="@contact.Id">
    <td>@contact.FirstName</td>
    <td>@contact.LastName</td>
    <td>@contact.CompanyName</td>
    <td>@contact.CreateDate.ToShortDateString()</td>
    <td>
        <a asp-action="Edit" asp-controller="Contact" asp-area="" asp-route-id="@contact.Id" class="btn btn-sm btn-secondary">Edit</a>
        <button class="btn btn-sm btn-danger btn-delete" onclick="remove('@contact.Id')">Delete</button>
    </td>
</tr>
} 
        }
        else
        {
<tr>
    <td colspan="5">
        <span>No record</span>
    </td>
</tr>
        }
    </tbody>
</table>

@section scripts {
    <script>
        function remove(id) {
            if (confirm("Emin misin?")) {
                $.post("@Url.Action("Delete", "Contact")/" + id, function (response) {
                    $("[data-id='" + id + "']").remove();
                });
            }
        }
    </script>
}

ContactCase.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ContactCase.Web/Views/Report/Index.cshtml
@{
    ViewData["Title"] = "Reports";
}
@model List<ReportModel>

<div class="text-center">
    <h1 class="display-4">Reports</h1>
</div>
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-header">
                <h4>New Report</h4>
            </div>
            <div class="card-body">

                <form asp-action="Create" asp-controller="Report" method="post" role="form" novalidate>
                    <div class="form-group">
                        <label for="Tag">Tag</label>
                        <input class="form-control" for="Tag"  name="Tag" />
                        <span validation-for="Tag" class="text-danger"></span>
                    </div>

                    <button type="submit" class="btn btn-sm btn-primary">Create Report</button>
                </form>

            </div>
        </div>
    </div>
</div>
<div class="row mt-5">
    <div class="col">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Tag</th>
                    <th>Count</th>
                    <th>CreateDate</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Any())
                {
                    @foreach (var report in Model)
                    {
                        <tr>
                            <td>@report.Tag</td>
                            <td>@(report.Count == 0 ? "N/A" : report.Count)</td>
                            <td>@report.CreateDate.ToShortDateString()</td>
                            <td>@report.Status</td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td colspan="5">
                            <span>No record.</span>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

</div>

ContactCase.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ContactCase.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ContactCase.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Index">Contacts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Report" asp-action="Index">Reports</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ContactCase.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>